"""
Deterministic next-step suggestions based on agent state.

These are appended to the LLM's response by the loop — NOT generated by the LLM.
Max 1-3 suggestions per state, following the natural audit flow.
"""

from __future__ import annotations

from ..types import AgentState


def _library_enabled() -> bool:
    """Check if the attribute training library is enabled."""
    try:
        from engines.config import ENABLE_ATTRIBUTE_LIBRARY
        return bool(ENABLE_ATTRIBUTE_LIBRARY)
    except Exception:
        return False


def _has_missing_frequencies(state: AgentState) -> bool:
    """Check if the loaded RCM has controls with missing/empty frequency values."""
    if state.rcm_df is None:
        return False
    df = state.rcm_df
    freq_col = None
    for col in df.columns:
        if col.lower().replace("_", " ").strip() in (
            "control frequency", "controlfrequency", "frequency",
            "control_frequency",
        ):
            freq_col = col
            break
    if not freq_col:
        return True
    for val in df[freq_col]:
        s = str(val).strip().lower()
        if not s or s in ("nan", "none", "null", "n/a", "na", "", "-",
                          "tbd", "to be determined", "not defined", "not specified"):
            return True
    return False


def _has_missing_risk_levels(state: AgentState) -> bool:
    """Check if the loaded RCM has controls with missing risk level data."""
    if state.rcm_df is None:
        return False
    df = state.rcm_df
    has_level = "risk_level" in df.columns
    has_prob = "risk_probability" in df.columns
    has_impact = "risk_impact" in df.columns

    if not has_level and not (has_prob and has_impact):
        return True
    if has_level:
        for val in df["risk_level"]:
            s = str(val).strip().lower()
            if not s or s in ("nan", "none", "null", "n/a", "na", "", "-", "tbd"):
                return True
    return False


def get_suggestions(state: AgentState, last_tool: str | None) -> str | None:
    """Return a formatted suggestions block (max 1-3 items), or None."""

    # ── Scoping intermediate phases (upload prompt) ──────────────────
    if state.scoping_awaiting_input and state.scoping_phase in (
        "ingested", "quantitative_done", "qualitative_done", "scoped_done",
    ):
        _UPLOAD_PROMPTS = {
            "ingested": (
                "You can download and review the exported accounts Excel. "
                "If anything needs adjusting, upload the modified file. "
                "Otherwise, we can move forward.\n\n"
                "**Upload a modified Excel** or **Continue with current results**?"
            ),
            "quantitative_done": (
                "The quantitative analysis is ready for your review. "
                "You can adjust which accounts are in-scope by editing the Excel.\n\n"
                "**Upload a modified Excel** or **Continue to qualitative analysis**?"
            ),
            "qualitative_done": (
                "The qualitative risk assessment is complete. "
                "You can fine-tune risk scores or factor assessments in the Excel.\n\n"
                "**Upload a modified Excel** or **Continue to final scoping**?"
            ),
            "scoped_done": (
                "Scoping is complete. You can review and adjust the final "
                "in-scope / out-of-scope decisions in the Excel.\n\n"
                "**Upload a modified Excel** or **Continue with these results**?"
            ),
        }
        prompt = _UPLOAD_PROMPTS.get(state.scoping_phase, "")
        if prompt:
            return f"\n\n---\n{prompt}"
        return None

    # ── Pending frequency inferences (awaiting approval) ─────────────
    if state.pending_frequency_inferences:
        return _format([
            "- **Make Changes** — Edit any control's frequency by telling me in chat, or download the Excel and re-upload it with your edits",
            "- **Approve & Apply** — Looks good — apply the inferred frequencies to the RCM and move on",
        ])

    # ── Pending risk level inferences (awaiting approval) ────────────
    if state.pending_risk_level_inferences:
        return _format([
            "- **Make Changes** — Edit any control's risk level, probability, or impact by telling me in chat, or download the Excel and re-upload with your edits",
            "- **Approve & Apply** — Looks good — apply the inferred risk levels to the RCM and move on",
        ])

    # ── After attribute preview (pending approval) ───────────────────
    if state.pending_tod_schemas or state.pending_toe_schemas:
        phase = "TOD" if state.pending_tod_schemas else "TOE"
        test_name = "Design" if phase == "TOD" else "Effectiveness"
        return _format([
            "- **Make Changes** — Add, edit, or remove testing attributes via chat or Excel upload",
            f"- **Approve & Run** — Attributes look good — proceed with the Test of {test_name}",
        ])

    # ── Document list generated (awaiting evidence folder) ───────────
    if (state.document_list_rows and not state.evidence_validated
            and last_tool == "run_test_of_design"):
        return _format([
            "- **Provide Evidence Folder** — Tell me the path to the folder containing your evidence files (organised by Control ID)",
        ])

    # ── After scoping complete ───────────────────────────────────────
    if state.scoping_phase == "complete" and not state.tod_results:
        return _format([
            "- **Continue to Testing** — Use the scoping output as the RCM and begin the Test of Design",
            "- **Upload a Different RCM** — Skip the scoping output and use your own RCM file instead",
        ])

    # ── After TOE ────────────────────────────────────────────────────
    if state.toe_results:
        items = [
            "- **Download Workpaper** — Save the completed TOE results as an Excel workpaper",
            "- **Review Results** — Walk through the TOD and TOE results side by side across all controls",
        ]
        if _library_enabled():
            items.append(
                "- **Save to Training Library** — Store these approved attributes so future audits can reuse them"
            )
        return _format(items)

    # ── After Sampling ───────────────────────────────────────────────
    if state.sampling_results and not state.toe_results:
        return _format([
            "- **Adjust Sample Counts** — Change any control's sample count via chat, or upload a modified Excel",
            "- **Continue to TOE** — Generate and preview the testing attributes for the Test of Effectiveness",
        ])

    # ── After TOD (before sampling) ──────────────────────────────────
    if state.tod_results and not state.sampling_results:
        has_failures = any(
            (getattr(r, "result", None) or (r.get("result") if isinstance(r, dict) else None)) == "FAIL"
            for r in state.tod_results
        )
        items = []
        if has_failures:
            items.append(
                "- **Remove Failed Controls** — Drop the controls that failed the Test of Design so only passing controls move forward"
            )
        items.append("- **Use KPMG Sampling** — Calculate sample sizes using the standard KPMG methodology")
        items.append("- **Use Custom Sampling** — Upload your own sampling table to determine sample sizes")
        return _format(items)

    # ── RCM loaded ───────────────────────────────────────────────────
    if state.rcm_df is not None and state.scoping_phase == "none":
        if _has_missing_frequencies(state):
            return _format([
                "- **Infer Missing Frequencies** — Automatically determine each control's frequency from its description",
            ])
        if _has_missing_risk_levels(state):
            return _format([
                "- **Use Default Scoring** — Compute risk levels using the standard weighted model (Low=1, Medium=3, High=6)",
                "- **Use Custom Scoring** — Provide your own score weights and/or band thresholds before computing",
            ])
        return _format([
            "- **Preview Testing Attributes** — Generate the testing attributes for the Test of Design and review them before running",
        ])

    return None


def _format(suggestions: list[str]) -> str:
    """Format the suggestions block — kept compact."""
    lines = "\n".join(suggestions)
    return f"\n\n---\n{lines}"
